[package]
name = "npmrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = {version = "0.11.22", features = ["blocking", "json", "gzip", "brotli", "deflate"]}
serde_json = "1.0.108"
openssl = { version = "0.10", features = ["vendored"] }
colored = "2.0.4"

[profile.release]
opt-level = 2
lto = true
